### PR TITLE
Update UI and cleaned up some code

### PR DESCRIPTION
**Pull request by pierredup**
* Change layout to full width
* Add circular progress bar for teams total PR count
* Inline chips next to name
* Update display of chips
* Calculate users progress as a percentage of the top user
* Display top user per team with a yellow progress
* Add icon and status next to PR in dialog
* Refactor and simplify some code

screen shot 2017-10-10 at 22 03 52
screen shot 2017-10-10 at 22 04 14

### CODE REVIEW

**Comment by royalmitten** [comment]
Looks awesome @pierredup!

If the top user per team is a tie between users, shouldn't the progress bar be yellow for all those users perhaps?

**Comment by pierredup** [comment]
Good point, or maybe it should not change color at all, since technically there is no top user then?

**Comment by royalmitten** [comment]
Yeah, maybe it's a good idea to not make it change color then, as the UI might get a bit busy if there are too many yellow bars.

**Comment by pierredup** [comment]
I'm going to merge this as-is for now, and will create a separate PR to handle when there is a tie

**Comment by royalmitten** [comment]
Sweet, no problem!

**Pull request merged**
