### PR TITLE
GitHub profile links

### PR DESCRIPTION
**Pull request by royalmitten**
- Open developer GitHub profile in a new tab, when clicking on their avatar in the PR dialog window
- Show a message when a developer has no PRs

image

### CODE REVIEW

**Comment by pierredup** [comment]
Thanks for this! I originally wanted to show a dialog with a list of all the PRs made, so it's easy to see which projects was contributed to. Maybe we can include different links for the profile and list of PRs then

**Comment by royalmitten** [comment]
@pierredup a dialog would be pretty cool! So when clicking on a user's avatar, we pop up a dialog and show the PRs they have made (we could probably add the link to their GitHub profile in the dialog as well then)?

**Comment by pierredup** [comment]
@royalmitten Take a look at #2, I added the dialog with the PR list, so we can probably either link the username to the github profile, or add the avatar in the dialog as well with the link

**Comment by royalmitten** [comment]
@pierredup, thanks, looks awesome.
I think it would look nice to add the avatar in the dialog and make that link to the user's profile.
If you're happy you can merge #2 and I'll update this PR with the changes?

**Comment by pierredup** [comment]
Done

**Comment by royalmitten** [comment]
Changes have been pushed as discussed

**Review by pierredup — APPROVED** [review]

**Pull request merged**
